document.addEventListener("DOMContentLoaded",function(){document.getElementById("seconddd").addEventListener("click",function(){window.location.href="next.html";window.webkitNotifications&&alert("Your web browser does support notifications!")})});function iii(){chrome.tabs.executeScript({code:'alert(document.title+" contains "+ $("a").length+" links ")'})}
function regCountryFind(){chrome.tabs.executeScript({code:'var myRegExp =[/Romania/g,/Italy/g,/Malaysia/g,/France/g,/Hauts-de-Seine/g];var myText = document.documentElement.innerHTML; for (var i=0; i<myRegExp.length; i++){if(myRegExp[i].test(myText)){alert("Found  Forbidden!");}else{} }'})}
function getGoogleMaps(){chrome.tabs.executeScript({code:'var hrefTrue =$("#livemap-link").attr("href");                                                  alert(hrefTrue); var $_GET = {};var __GET = hrefTrue/*window.location.search*/.substring(9).split("&"); for(var i=0; i<__GET.length; i++) { var getVar = __GET[i].split("=");   $_GET[getVar[0]] = typeof(getVar[1])=="undefined" ? "" : getVar[1]; }       alert($_GET["lon"]+" : "+$_GET["lat"]);var a=$_GET["lon"];if($_GET["lon"]>120.0001 && $_GET["lon"]<122.61 && $_GET["lat"]<19.409&& $_GET["lat"]>5.511594){alert("Philippines");} if (confirm("Navigate to Street View?")==true) { window.open("https://www.instantstreetview.com/@"+$_GET["lat"]+"," +$_GET["lon"] +",-50.9h,5p,1z", "_blank"); }'})}
function getLivemapCoord2(){chrome.tabs.executeScript({code:'var hrefTrue =$("#livemap-link").attr("href");                                                  alert(hrefTrue); var $_GET = {};var __GET = hrefTrue.substring(9).split("&"); for(var i=0; i<__GET.length; i++) { var getVar = __GET[i].split("=");   $_GET[getVar[0]] = typeof(getVar[1])=="undefined" ? "" : getVar[1]; }       alert($_GET["lon"]+" : "+$_GET["lat"]);window.lonLive=$_GET["lon"];alert(lonLive); '})}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("test").addEventListener("click",function(){getLivemapCoord2()})});
function getCountry(){chrome.tabs.executeScript({code:'var $_GET = {};var __GET = window.location.search.substring(1).split("&"); for(var i=0; i<__GET.length; i++) { var getVar = __GET[i].split("=");   $_GET[getVar[0]] = typeof(getVar[1])=="undefined" ? "" : getVar[1]; }     /* alert($_GET["lon"]+" : "+$_GET["lat"]);*/var a=$_GET["lon"];if($_GET["lon"]>120.0001 && $_GET["lon"]<122.61 && $_GET["lat"]<19.409&& $_GET["lat"]>5.511594){alert("Philippines");} '})}
document.addEventListener("DOMContentLoaded",function(){for(var a=document.getElementsByTagName("a"),c=0;c<a.length;c++)(function(){var b=a[c],d=b.href;b.onclick=function(){chrome.tabs.create({active:!0,url:d})}})()});document.addEventListener("DOMContentLoaded",function(){document.getElementById("l").addEventListener("click",function(){iii()})});function hellYeah(a){$(event.target);a=$(document.documentElement).find("a").length;alert("There are "+a+" links on this  page ")}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("getURL").addEventListener("click",function(){getGoogleMaps()})});$("#imgL").hover(function(){$("#imgL").fadeOut(200,function(){$(this).attr("src","images/fff2.png").bind("onreadystatechange load",function(){this.complete&&$(this).fadeIn(300)})})},function(){$("#imgL").fadeOut(200,function(){$(this).attr("src","images/extenn.png").bind("onreadystatechange load",function(){this.complete&&$(this).fadeIn(300)})})});
try{$(document).ready(function(){chrome.runtime.sendMessage({action:"createAlarm"});chrome.runtime.onMessage.addListener(function(a,c,b){})})}catch(a){"rigged"}var w=window;/https:\/\/docs.google.com\/spreadsheets/.test(w.location.href)&&alert("You are in GoogleDocs");
if(/https:\/\/docs.google.com/.test(w.location.href)){var sec=function(){var a=new Date,c=a.getHours(),b=a.getMinutes(),d=c+":"+b;iC=parseInt(c);iC-=9;88!=b&&89!=b||alert("          Attention - TEST MODE\n\n           Iteration => "+iC+"\n           Time is : "+d+"\n"+a);40==b&&12==c&&alert("Lunch time");40==b&&17==c&&alert("Time to Go home")};setInterval(sec,6E4);sec();try{document.body.style.backgroundImage="url('http://www.helinstrading.com/icon/google-icon.png')",document.getElementsByClassName("ss-header-image-sizer")[0].remove(),
document.getElementsByClassName("ss-form-title")[0].remove(),document.getElementsByClassName("ss-form-desc ss-no-ignore-whitespace")[0].remove(),document.getElementsByClassName("ss-form-container")[0].style.backgroundImage="url('http://data.whicdn.com/images/25614625/original.png')"}catch(a){}}
if(/https:\/\/www.waze.com/.test(w.location.href)||/https:\/\/editor-beta.waze.com/.test(w.location.href)){var checkAnyCountryIfScrolled=function(){setTimeout(function(){var a=(new Date).getSeconds();window.secThen=15;secThen=a},30)},checkAllCountriesAtOnce=function(){checkAnyCountry(-85.883097,-82.700812,11.186147,8.359923,"Costa Rica");checkAnyCountry(6.806093,15.972735,45.862255,36.336099,"Italy");checkAnyCountry(100.103655,103.55837,4.863989,2.138495,"Malaysia");checkAnyCountry(111.496965,117.087732,
5.295168,1.953356,"Malaysia!")},checkAnyCountry=function(a,c,b,d,e){lon>a&&lon<c&&lat<b&&lat>d&&(window.ccc=e,window.flaggg="off",$("body").append('<center><div id="pppv" style="display:none;position:absolute;top:150px;z-index:55;right:20%;"><H1 id="h1" style="background:white;font-weight: bold;"><script>document.getElementById("h1").innerHTML=ccc;\x3c/script></H1><img src="http://creativesafetypublishing.com/wp-content/uploads/2015/01/danger-construction-area-label.jpg"></div></center>'),setTimeout(function(){$("#pppv").show(1500)},
3E3),$("#pppv").click(function(){$("#pppv").hide(1500);setTimeout(function(){window.flaggg="on"},15E3)}))},getLivemapCoord=function(){var a=$("#livemap-link").attr("href");alert(a);for(var c={},a=a.substring(9).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");c[d[0]]="undefined"==typeof d[1]?"":d[1]}alert(c.lon+" : "+c.lat);window.lonLive=c.lon;alert(lonLive)},getLonLat=function(){for(var a={},c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");a[d[0]]="undefined"==
typeof d[1]?"":d[1]}window.lon=a.lon;window.lat=a.lat;return lon};window.flaggg="on";getLonLat();checkAllCountriesAtOnce();var last_moved=0;$(document).mousemove(function(a){a=a.timeStamp;if(1E3<a-last_moved){if("on"==window.flaggg){checkAllCountriesAtOnce();var c=document.getElementById("test");c&&c.focus()}last_moved=a}})}
document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("imgL"),c=["images/fff2.png","images/extenn.png","images/smile2.png"],b;a.addEventListener("click",function(){var d=Math.round(2*Math.random());d==b&&(d=Math.round(2*Math.random()));b=d;a.src=c[d]})});var data_url="http://api.openweathermap.org/data/2.5/weather?q=Kyiv&APPID=42b614437754a4ec7c704604e2a3f97f";
getWeather(function(a){var c=a.main.temp,c=Math.round(c-272),b=a.weather[0].description;a=a.weather[0].description+"; temperature: "+c+"C ; wind: "+a.wind.speed+"km/h";WeathPicture="rain"==b||"light rain"==b?"http://www.veryicon.com/icon/ico/System/Icons8%20Metro%20Style/Weather%20Rain.ico":"clouds"==b||"broken clouds"==b||"scattered clouds"==b?"http://www.clipartbest.com/cliparts/4cb/KRM/4cbKRMXXi.png":"snow"==b||"light snow"==b||"heavy snow"==b?"https://upload.wikimedia.org/wikipedia/commons/b/bb/Snow_flake_icon.png":
"http://findicons.com/files/icons/2603/weezle/256/weezle_sun.png";a=a+"<br><img  src="+WeathPicture+">";document.getElementById("weather").innerHTML="Check"+a});function getWeather(a){$.ajax({dataType:"jsonp",url:data_url,success:a})};
